chore: update pipeline

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -12,31 +12,30 @@ jobs:
     strategy:
       matrix:
         node-version: [22.x]
-
     steps:
-    - uses: actions/checkout@v4
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
-    - run: npm run build
-    - name: Validate build folder
-      run: |
-        if [ -d build ] && [ "$(ls -A build)" ]; then
-          echo "Build folder exists and is not empty."
-        else
-          echo "Build folder is missing or empty. Failing the job."
-          exit 1
-        fi
-    - name: Archive build
-      run: tar -czf build.tar.gz ./build
-    - name: Upload build artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: build-artifact
-        path: build.tar.gz
+      - uses: actions/checkout@v4
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+      - run: npm ci
+      - run: npm run build
+      - name: Validate build folder
+        run: |
+          if [ -d build ] && [ "$(ls -A build)" ]; then
+            echo "Build folder exists and is not empty."
+          else
+            echo "Build folder is missing or empty. Failing the job."
+            exit 1
+          fi
+      - name: Archive build
+        run: tar -czf build.tar.gz ./build
+      - name: Upload build artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: build-artifact
+          path: build.tar.gz
 
   test:
     runs-on: ubuntu-latest
@@ -44,31 +43,30 @@ jobs:
     strategy:
       matrix:
         node-version: [22.x]
-
     steps:
-    - uses: actions/checkout@v4
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
-    - run: npm run test
+      - uses: actions/checkout@v4
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+      - run: npm ci
+      - run: npm run test
 
   add-ip:
     runs-on: ubuntu-latest
     needs: test
     steps:
-    - name: Get Github action IP
-      id: ip
-      uses: haythem/public-ip@v1.2
-    - name: Add Github Actions IP to Security group
-      run: |
-        aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+      - name: Get Github action IP
+        id: ip
+        uses: haythem/public-ip@v1.2
+      - name: Add Github Actions IP to Security group
+        run: |
+          aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
 
   deploy-code:
     runs-on: ubuntu-latest
@@ -79,17 +77,14 @@ jobs:
         with:
           name: build-artifact
           path: .
-      
       - name: Set up SSH key
         run: |
           mkdir -p ~/.ssh
           echo "$SSH_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-      
       - name: Test SSH connection
         run: |
           ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST_IP }} "echo SSH connection successful"
-      
       - name: Install NVM and Node.js on EC2
         run: |
           ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST_IP }} << 'EOF'
@@ -99,29 +94,27 @@ jobs:
             nvm use 22
             npm install -g pm2
           EOF
-      
       - name: Deploy build to prod server
         run: |
           ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST_IP }} "mkdir -p /home/ec2-user/user-microservice"
           scp -i ~/.ssh/id_rsa ./build.tar.gz ec2-user@${{ secrets.HOST_IP }}:/home/ec2-user/user-microservice/build.tar.gz
-
       - name: Extract build on EC2
         run: |
           ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST_IP }} "tar -xzf /home/ec2-user/user-microservice/build.tar.gz -C /home/ec2-user/user-microservice"
           ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.HOST_IP }} "cd /home/ec2-user/user-microservice && npm install --production && pm2 restart user-microservice"
-      env:
-        SSH_KEY: ${{ secrets.SSH_KEY }}
-        HOST_IP: ${{ secrets.HOST_IP }}
+        env:
+          SSH_KEY: ${{ secrets.SSH_KEY }}
+          HOST_IP: ${{ secrets.HOST_IP }}
 
   remove-ip:
     runs-on: ubuntu-latest
     needs: deploy-code
     steps:
-    - name: Remove Github Actions IP from security group
-      run: |
-        aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
-      if: always()
+      - name: Remove Github Actions IP from security group
+        run: |
+          aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+        if: always()
